### PR TITLE
bsDuallistbox.js

### PR DESCRIPTION
**Pull request by Xainu31**
Safe naming must be done otherwise we will have errors in minification

### CODE REVIEW

**Comment by frapontillo** [comment]
The file is already annotated and minified in the `dist` directory.

**Comment by Xainu31** [comment]
While using Microsoft bundling it bundles the original Js if no minified version is found so it would always be better to use safe naming

**Comment by frapontillo** [comment]
But *there is* a minified version in the package already... You should reference that one or force the .NET bundling to do so. Or, get rid of that useless system and use proper dev tools.

**Comment by Xainu31** [comment]
That's harsh... Always use safe naming.. :)

**Comment by frapontillo** [comment]
There's a preprocessor that does the job for me ([ng-annotate](https://github.com/olov/ng-annotate)), and pretty much every angular module that you'll find on GitHub uses the same approach of never including explicit annotations in source code.

**Pull request closed without merging**
